# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import shadowstream_pb2 as shadowstream__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in shadowstream_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class IngestorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PushChange = channel.unary_unary(
                '/shadowstream.Ingestor/PushChange',
                request_serializer=shadowstream__pb2.ChangeRecord.SerializeToString,
                response_deserializer=shadowstream__pb2.PushResponse.FromString,
                _registered_method=True)


class IngestorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PushChange(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_IngestorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PushChange': grpc.unary_unary_rpc_method_handler(
                    servicer.PushChange,
                    request_deserializer=shadowstream__pb2.ChangeRecord.FromString,
                    response_serializer=shadowstream__pb2.PushResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shadowstream.Ingestor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shadowstream.Ingestor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Ingestor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PushChange(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shadowstream.Ingestor/PushChange',
            shadowstream__pb2.ChangeRecord.SerializeToString,
            shadowstream__pb2.PushResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ReplayerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReplayEvent = channel.unary_unary(
                '/shadowstream.Replayer/ReplayEvent',
                request_serializer=shadowstream__pb2.ReplayRequest.SerializeToString,
                response_deserializer=shadowstream__pb2.ReplayResponse.FromString,
                _registered_method=True)


class ReplayerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReplayEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReplayerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReplayEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplayEvent,
                    request_deserializer=shadowstream__pb2.ReplayRequest.FromString,
                    response_serializer=shadowstream__pb2.ReplayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shadowstream.Replayer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shadowstream.Replayer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Replayer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReplayEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shadowstream.Replayer/ReplayEvent',
            shadowstream__pb2.ReplayRequest.SerializeToString,
            shadowstream__pb2.ReplayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
