# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: shadowstream.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'shadowstream.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12shadowstream.proto\x12\x0cshadowstream\"\x8e\x02\n\x0c\x43hangeRecord\x12\x0b\n\x03lsn\x18\x01 \x01(\t\x12\x13\n\x0b\x63ommit_time\x18\x02 \x01(\x03\x12\r\n\x05table\x18\x03 \x01(\t\x12\x11\n\toperation\x18\x04 \x01(\t\x12\x30\n\x03old\x18\x05 \x03(\x0b\x32#.shadowstream.ChangeRecord.OldEntry\x12\x30\n\x03new\x18\x06 \x03(\x0b\x32#.shadowstream.ChangeRecord.NewEntry\x1a*\n\x08OldEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a*\n\x08NewEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x1f\n\x0cPushResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"`\n\rReplayRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12)\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x1a.shadowstream.ChangeRecord\x12\x14\n\x0cvirtual_time\x18\x03 \x01(\x03\"!\n\x0eReplayResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32P\n\x08Ingestor\x12\x44\n\nPushChange\x12\x1a.shadowstream.ChangeRecord\x1a\x1a.shadowstream.PushResponse2T\n\x08Replayer\x12H\n\x0bReplayEvent\x12\x1b.shadowstream.ReplayRequest\x1a\x1c.shadowstream.ReplayResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'shadowstream_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHANGERECORD_OLDENTRY']._loaded_options = None
  _globals['_CHANGERECORD_OLDENTRY']._serialized_options = b'8\001'
  _globals['_CHANGERECORD_NEWENTRY']._loaded_options = None
  _globals['_CHANGERECORD_NEWENTRY']._serialized_options = b'8\001'
  _globals['_CHANGERECORD']._serialized_start=37
  _globals['_CHANGERECORD']._serialized_end=307
  _globals['_CHANGERECORD_OLDENTRY']._serialized_start=221
  _globals['_CHANGERECORD_OLDENTRY']._serialized_end=263
  _globals['_CHANGERECORD_NEWENTRY']._serialized_start=265
  _globals['_CHANGERECORD_NEWENTRY']._serialized_end=307
  _globals['_PUSHRESPONSE']._serialized_start=309
  _globals['_PUSHRESPONSE']._serialized_end=340
  _globals['_REPLAYREQUEST']._serialized_start=342
  _globals['_REPLAYREQUEST']._serialized_end=438
  _globals['_REPLAYRESPONSE']._serialized_start=440
  _globals['_REPLAYRESPONSE']._serialized_end=473
  _globals['_INGESTOR']._serialized_start=475
  _globals['_INGESTOR']._serialized_end=555
  _globals['_REPLAYER']._serialized_start=557
  _globals['_REPLAYER']._serialized_end=641
# @@protoc_insertion_point(module_scope)
